name: CI
on:
  pull_request:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
#        IDEA_VERSION: [ 2021.1, 2022.1.4, 2022.2.1 ]
        IDEA_VERSION: [ 2023.2, LATEST-EAP-SNAPSHOT ]
        WITH_IDEA_PLUGINS: [ true, false ]
        include:
          - IDEA_VERSION: 2023.2
            SCALA_PLUGIN_VERSION: 2023.2.23

          - IDEA_VERSION: LATEST-EAP-SNAPSHOT
            SCALA_PLUGIN_VERSION: 2024.1.1
          #            UPLOAD_TEST_RESULTS: true

    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      IDEA_VERSION: ${{ matrix.IDEA_VERSION }}
      WITH_IDEA_PLUGINS: ${{ matrix.WITH_IDEA_PLUGINS }}
      SCALA_PLUGIN_VERSION: ${{ matrix.SCALA_PLUGIN_VERSION }}
