name: Test EAP
on:
  schedule:
    - cron:  '0 12 * * *'  # execute daily at 12:00

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        WITH_IDEA_PLUGINS: [ true, false]
        include:
          - IDEA_VERSION: LATEST-EAP-SNAPSHOT
            SCALA_PLUGIN_VERSION: 2024.1.1

          - IDEA_VERSION: LATEST-EAP-SNAPSHOT
            SCALA_PLUGIN_VERSION: 2024.1.1
            WITH_IDEA_PLUGINS: true

    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      IDEA_VERSION: ${{ matrix.IDEA_VERSION }}
      WITH_IDEA_PLUGINS: ${{ matrix.WITH_IDEA_PLUGINS }}
      SCALA_PLUGIN_VERSION: ${{ matrix.SCALA_PLUGIN_VERSION }}